"""create models

Revision ID: e437b7899491
Revises: 5ac9a3af7f29
Create Date: 2024-09-22 06:05:51.334701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e437b7899491'
down_revision: Union[str, None] = '5ac9a3af7f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_results_id'), 'sentiment_results', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_results_symbol'), 'sentiment_results', ['symbol'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_sentiment_results_symbol'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    # ### end Alembic commands ###
